const tagsData = [
  { name: 'React', color: 'magenta' },
  { name: 'Javascript', color: '#556B2F' },
  { name: 'Electron', color: '#556B2F' },
  { name: 'Tensorflow', color: '#556B2F' },
  { name: 'Python', color: 'magenta' },
  { name: 'Node', color: '#B22222' },
  { name: 'Vue', color: 'magenta' },
  { name: 'React Native', color: 'red' },
  { name: 'Typescript', color: 'purple' },
  { name: 'HTML', color: '#556B2F' },
  { name: 'CSS', color: 'blue' },
  { name: 'Koa2', color: 'green' },
  { name: 'Express', color: '#808000' },
  { name: 'Mysql', color: '#6495ED' },
  { name: 'Git', color: 'magenta' },
  { name: 'Parcel', color: '#556B2F' },
  { name: 'Webpack', color: 'magenta' },
  { name: 'Regex', color: '#808080' },
  { name: 'Sequelize', color: '#A0522D' },
  { name: 'ECS', color: '#A0522D' },
  { name: 'Windows', color: '#A0522D' },
  { name: 'Linux', color: '#A0522D' },
  { name: 'Other', color: '#A0522D' },
  { name: '小程序', color: '#A0522D' },
  { name: 'Flutter', color: '#A0522D' },
  { name: 'Django', color: '#A0522D' },
  { name: 'Flask', color: '#A0522D' },
  { name: 'Scrapy', color: '#A0522D' },
  { name: 'Java', color: '#A0522D' },
  { name: 'Blockchain', color: '#A0522D' },
  { name: 'Solidity', color: '#A0522D' },
  { name: 'Raspberry Pi', color: '#A0522D' },
  { name: 'Golang', color: '#A0522D' },
]

export { tagsData }
